name: deploy
on: 
   push:
    branches: |
        gh-page

jobs: 
    deploy:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'gh-deploy')
        steps:
           - name: ------deploy-------
             uses: actions/checkout@v4

           - name: Push changes to another repository
             run: |
               git remote add origin https://github.com/handthen/web.git
               git push -f origin master
             env:
               GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
