# workflow 名称
name: Build
# 触发事件
on:
  # push 事件，master分支时触发
  push:
    branches:
      - master
# 工作流，执行的东西
jobs:
  build:
    # 运行器
    runs-on: ubuntu-latest
    # 提交信息包含deploy 时触发
    if: contains(github.event.head_commit.message, 'deploy')
    steps:
      # 拷贝代码到虚拟机
      - name: -------Checkout-------
        uses: actions/checkout@v4
      # 设置node 版本与源
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: -------Install-------
        run: |
          npm install

      - name: -------Build-------
        run: |
          npm run build

      - name: -------Deploy-------
        # 使用JamesIves/github-pages-deploy-action 库
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          # 推送到哪个分支上
          branch: master
          # 推送哪个文件里的内容
          folder: dist
          # 是否强制提交
          force: true
          # 提交时候的 commit 消息
          commit-message: gh-deploy
          # 提交到哪个仓库的，默认是本仓库，所以这里也可以忽略不写
          repository-name: handthen/web
        env:
          GITHUB_TOKEN: ${{ secrets.WEB_SECRET }}
